services:
  app:
    container_name: simple-form-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    networks:
      - simple-form-net
    volumes:
      - .:/srv

  db:
    container_name: simple-form-db
    image: mariadb:11.4.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_form
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simple-form-net

networks:
  simple-form-net:
    driver: bridge

volumes:
  db_data: